#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-OneHundredNotOut
version:      100
version_from: OneHundredNotOut.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
